"""empty message

Revision ID: 4c8f29d66ec4
Revises: 
Create Date: 2020-12-15 04:37:29.395181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8f29d66ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute('''
    insert into "actors" (name, age, gender)
    values ('actor_01',20,'male'),
    ('actor_02',25,'male'),
    ('actor_03',30,'female'),
    ('actor_04',35,'female'),
    ('actor_05',40,'male')
    ''')

    op.execute('''
    insert into "movies" (title, release_date)
    values ('movie_01','1-12-2020'),
    ('movie_02','2-12-2020'),
    ('movie_03','3-12-2020'),
    ('movie_04','4-12-2020'),
    ('movie_05','5-12-2020')
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
